bacilicsk-phase1/bacilicsk/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('', include(("users.urls", "users"), namespace="users")),
    path('admin/', admin.site.urls),
    path('codes/', include(("codes.urls", "codes"), namespace="codes")),
]

bacilicsk-phase1/codes/urls.py
from django.urls import path

from . import views

urlpatterns=[
    path('', views.index, name="index"),
    path('savecode/',views.save_code, name="codesave"),
    path('mycodes/', views.view_codes, name="mycodes"),
    path('show/<str:file>', views.show_file, name="show_file"),
    path('delete/<str:file>', views.delete_file, name="delete_file"),
    path('update/<str:file>', views.update_file, name="update_file")
]

bacilicsk-phase1/users/urls.py
from django.urls import path

from . import views

urlpatterns=[
    path('', views.index, name="index"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('signup/', views.signup_view, name="signup"),
]

bacilicsk-phase1/codes/views.py
from django.contrib.auth.models import User
from django.http import request
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse
from .models import Code
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def index(request):
    if request.user.is_authenticated:
        return render(request, "codes/index.html")
    else:
        return HttpResponseRedirect(reverse("users:index"))

def save_code(request):
    if request.user.is_authenticated:
        language=request.POST['lang']
        code_text=request.POST['codetext']
        fname=request.POST['saveas']
        code=Code(lang=language, code=code_text, coder=request.user, name=fname)
        code.save()
        return HttpResponseRedirect(reverse("users:index"))
    else:
        return HttpResponseRedirect(reverse("users:index"))

def view_codes(request):
    codes=Code.objects.all().filter(coder=request.user)
    return render(request, "codes/allcodes.html",{
        "codes":codes
    })

def show_file(request, file):
    code=Code.objects.get(coder=request.user, name=file)
    return render(request, "codes/showcode.html",{
        "code": code.code,
        "name": code.name
    })

def delete_file(request, file):
    Code.objects.get(coder=request.user, name=file).delete()
    codes=Code.objects.all().filter(coder=request.user)
    return render(request, "codes/allcodes.html",{
        "codes":codes
    })

def update_file(request, file):
    if request.method=="POST":
        new_code=request.POST["new_code"]
        code=Code.objects.get(coder=request.user, name=file)
        code.code=new_code
        code.save()
        codes=Code.objects.all().filter(coder=request.user)
        return render(request, "codes/allcodes.html",{
            "codes":codes
        })

bacilicsk-phase1/users/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.models import User
# Create your views here.
def index(request):
    if request.user.is_authenticated:
        return render(request, "users/index.html")
    else:
        return HttpResponseRedirect(reverse('users:login'))

def login_view(request):
    if request.method!="POST":
        return render(request, "users/login.html")
    else:
        username=request.POST['username']
        password=request.POST['password']
        user=authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("users:index"))
        else:
            return render(request, "users/login.html", {
                "message":"Invalid Credentials"
            })

def logout_view(request):
    logout(request)
    return render(request, "users/login.html", {
        "message":"Logged out successfully"
    })

def signup_view(request):
    if request.method=="GET":
        return render(request, "users/signup.html")
    else:
        username=request.POST['username']
        password=request.POST['password']
        email=request.POST['email']
        firstname=request.POST['first_name']
        lastname=request.POST['last_name']
        user=User.objects.create_user(username, email, password)
        user.last_name=lastname
        user.first_name=firstname
        user.save()
        return HttpResponseRedirect(reverse("users:login"))

bacilicsk-phase1/codes/templates/codes/allcodes.html
{% extends "codes/layout.html" %}

{% block body %}
    {% if  not codes %}
        <li>No saved codes</li>
    {% endif %}

        {% for code in codes%}
        <div>
            <a href="../show/{{code.name}}">{{code}}</a> 
            <a href="../delete/{{code.name}}">Delete</a>
        </div>
            
        {% endfor %}
    <br><br>
    <a href="/">Back to Home</a>
{% endblock %}

bacilicsk-phase1/codes/templates/codes/index.html
{% extends "codes/layout.html" %}

{% block body %}
    <h1>Happy Coding {{request.user.first_name}}</h1>

    <form action="{% url 'codes:codesave' %}" method="POST">
        {% csrf_token %}
        <label>Select Programming language</label><br>
        <input type="radio" name="lang" value="C" id="C">
        <label for="C">C++</label>
        <input type="radio" name="lang" value="P" id="P">
        <label for="P">Python</label>
        <input type="radio" name="lang" value="J" id="J">
        <label for="J">Java</label> 
        <br>
        <textarea rows="30" cols="100" name="codetext">Code here</textarea><br>
        <label>Save as</label>
        <input type="text" name="saveas">
        <br>
        <button type="submit">Submit</button>
    </form>

    <a href="{% url 'users:index' %}">Back to Home</a>
{% endblock %}

bacilicsk-phase1/codes/templates/codes/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Code</title>
        <link rel="stylesheet" href="{% static 'codes/styles.css' %}">
    </head>
    <body>
        {% block body %}
        
        {% endblock %}
    </body>
</html>

bacilicsk-phase1/codes/templates/codes/showcode.html
{% extends "codes/layout.html" %}

{% block body %}
    <h1>{{name}}</h1>

    <form action="../update/{{name}}", method="POST">
        {% csrf_token %}
        <textarea rows="30" cols="100" name="new_code">{{code}}</textarea><br>
        <button type="submit">Save</button>
    </form>
    <a href="{% url 'codes:mycodes' %}">Back to My Codes</a>
{% endblock %}

bacilicsk-phase1/users/templates/users/index.html
{% extends "users/layout.html" %}

{% block body %}
    Hello {{ request.user.username }}

    <header>
        <nav>
            <a href="{% url 'codes:index' %}">New Code</a>
            <a href="{% url 'codes:mycodes' %}">My Codes</a>
        </nav>
    </header>
    <ul>
        <li>Username: {{request.user.username}}</li>
        <li>Email: {{request.user.email}}</li>
    </ul>
    <br>
    <a href="{% url 'users:logout' %}">LogOut</a>
{% endblock %}

bacilicsk-phase1/users/templates/users/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Users</title>
        <link rel="stylesheet" href="{% static 'users/styles.css' %}">
    </head>
    <body>
        {% block body %}

        {% endblock %}
    </body>
</html>

bacilicsk-phase1/users/templates/users/login.html
{% extends "users/layout.html" %}

{% block body %}
    <h1>BACILICSK</h1>
    <h1>User Login</h1>

    {% if message %}
        <p>{{message}}</p>
    {% endif %}

    <form action="{% url 'users:login' %}" method="POST">
        {% csrf_token %}
        Username: <input type="text" name="username"><br><br>
        Password: <input type="password" name="password"><br><br>
        <input type="submit" value="login">
    </form>

    <a href="{% url 'users:signup' %}">New User? Register Here</a>
{% endblock %}

bacilicsk-phase1/users/templates/users/signup.html
{% extends "users/layout.html" %}

{% block body %}
    <h1>SignUp</h1>

    <form action="{% url 'users:signup'%}" method="POST">
        {% csrf_token %}
        Username: <input type="text" name="username" placeholder="Username"><br>
        First Name: <input type="text" name="first_name" placeholder="First Name"><br>
        Last Name: <input type="text" name="last_name" placeholder="Last Name"><br>
        Email: <input type="email" name="email" placeholder="email-address"><br>
        Password: <input type="password" name="password" placeholder="Password"><br>
        Confirm Password: <input type="password" name="confirm_password" placeholder="Confirm Password"><br><br>
        <button type="submit">Sign Up!</button>
    </form>

    <a href="{% url 'users:login' %}">Already A User? Sign In</a>
{% endblock %}